### ISSUE TITLE
Buil fails with UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined     at writeFile (fs.js:1436:5)

### ISSUE THREAD

**Issue by mitselek** [poff-bnff/web2021#678]
**Describe the bug**
Build fails with
> UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined at writeFile (fs.js:1436:5)

**To Reproduce**
no idea

**Research**

**Comment by mitselek** [comment]
Läksin edasi tehes viimasest toimivast commitist uue haru
[Update strapi.rest](https://github.com/poff-bnff/web2021/commit/2419db6ec5b9682f41b1491a78fb95c54ad0420c) -> [back-to-before-the-big-fail](https://github.com/poff-bnff/web2021/tree/back-to-before-the-big-fail)
